services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
  web:
    build: "./src"
    restart: always
    container_name: trawsgrifiwr.techiaith.cymru
    command: ["revel", "run", "-a", ".", "dev"]
    volumes:
      - "./src/app:/usr/src/app"
    ports:
      - "7070:9000"
    depends_on:
      - redis
volumes:
  redis_data: {}

