services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
  web:
    build: "./src"
    restart: always
    container_name: dev-trawsgrifiwr.techiaith.cymru
    command: ["revel", "run", "-a", ".", "dev"]
    volumes:
      - my-volume:/usr/src/app
      - "./src/app:/usr/src/app"
      - "./data/recordings:/data/recordings"
    ports:
      - "7770:9000"
    depends_on:
      - redis
#  test:
#    build:
#      dockerfile: "./DockerfileTests"
#    container_name: test-trawsgrifiwr
#    command: ["go", "test"]
#    volumes:
#      - "./src/app:/usr/src/app"
#      - "./data/recordings:/data/recordings"

volumes:
  redis_data: {}
  my-volume: {}

