package models

var simpleTestSegments = []Segment{
	{
		ID:    0,
		Start: 0.009,
		End:   7.876,
		Text:  "a",
	},
	{
		ID:    1,
		Start: 8.116,
		End:   16.364,
		Text:  "b",
	},
}

var testSegments = []Segment{
	{
		ID:    0,
		Start: 0.009,
		End:   7.876,
		Text:  "Mae'r byd tu allan wedi troi yn rhywle ansicr a peryg gyda Covid-19 yn lladd miloedd.",
	},
	{
		ID:    1,
		Start: 8.116,
		End:   16.364,
		Text:  "Mae'r llywodraeth yn gorfodi ni i aros tu fewn, dim cymdeithasu, cadw pellter a gwisgo masgiau.",
	},
	{
		ID:    2,
		Start: 17.404,
		End:   20.227,
		Text:  "Mae hyn yn creu gorbryder ac agor y ffôn.",
	},
	{
		ID:    3,
		Start: 22.415,
		End:   48.989,
		Text:  "mae ambellyn yn meddwl bod rhywbeth arall yn fain beth sydd wedi achosi y sefyllfa erchyll yn llefus yma go wir dyna dan ni'n drafod heddiw ar Odpeth",
	},
	{
		ID:    4,
		Start: 49.465,
		End:   53.506,
		Text:  "jyst i esbonio ma' gynna ma' gynna Elin a fi yy cath.",
	},
	{
		ID:    5,
		Start: 53.526,
		End:   55.327,
		Text:  "O allan gyfarchiadau ar y piodas.",
	},
	{
		ID:    6,
		Start: 55.487,
		End:   56.287,
		Text:  "Diolch ia.",
	},
	{
		ID:    7,
		Start: 56.327,
		End:   58.428,
		Text:  "diolch Iwan allan gyfarchiadau ar fod yn best man.",
	},
	{
		ID:    8,
		Start: 58.828,
		End:   65.69,
		Text:  "O diolch so ia yym so yr teulu pits ŵan dan ni de yn edrych ar yym technically ia.",
	},
	{
		ID:    9,
		Start: 65.79,
		End:   79.194,
		Text:  "Odpeth so gynnon ni yym yy Iwan pits ydw i wrth gwrs yy dwi'n yym ia dwi'n dwi'n supernatural enthusiast yym dwi'n geshi fy eni ar Halloween dwi'n meddwl hwnna oedd o'n dechra.",
	},
	{
		ID:    10,
		Start: 79.718,
		End:   108.077,
		Text:  "ie ie yym ma' hwnna'n neud sense ti'n gwybod hwnna oedd yn egluro pob dim rili dwi'n cofio pan oedden ni'n blant yy Hywel Pitt dwi gyda llaw brawd Iwan Pitt ia helo Hywel helo yym dwi yy dwi'n cofio pan oedden ni'n fy ngach fatha ag o'n i'n rili ifanc ond oedd gynnon ni ryw lyfr fatha hardback fatha rili trwchus efo llwy- fatha jyst jyst basically fatha ryw encyclopaedia o horror films.",
	},
	{
		ID:    11,
		Start: 108.473,
		End:   110.554,
		Text:  "o ia Fangoria!",
	},
	{
		ID:    12,
		Start: 110.594,
		End:   111.395,
		Text:  "Ie Fangoria.",
	},
	{
		ID:    13,
		Start: 111.555,
		End:   118.678,
		Text:  "Ie annual Fangoria oedd o yym so os dach chi fatha ddim yn gwbod ella bo' chdi'm yn gwbod fel ond yym na na dwi ddim.",
	},
	{
		ID:    14,
		Start: 119.199,
		End:   136.948,
		Text:  "oedd Fangoria oedd yy oedd Fangoria'n cyfres o magazines mm yym oedden nhw'n so oedden nhw'n reviewio yym agen edrych ar behind the scenes ma' cath oh my god oedd mi wbrando a knockio'r board drosodd oedd yym ma'r ma'r recording device ar.",
	},
	{
		ID:    15,
		Start: 137.671,
		End:   156.643,
		Text:  "yym ia so ma Fangoria magazine yy horror magazine mhm so fatha ti'n ga'l tibod fatha yym ma' ma' miw newydd brathu elin fysa di dda i jyst cadw ddistaw arna elin ma- mae'n ciwt ond mae'n mae'n ddat weithiau de yndi mae'n absolutely mental so yym",
	},
	{
		ID:    16,
		Start: 157.09,
		End:   186.572,
		Text:  "ia nath yym o'd o'd Fangoria yn magazine fedrwch chi gwglo fo neu whatever ond Horror magazine o'dd o a o'dd o'n new efo ryw llyfr fatha The Big Bumper Book o Fangoria o'dd o basically yr erthygla gora o'r magazine drosto'r fatha dwi'm yn gwbod os o'dd o'n se- fatha celebration deg mlynadd ta blwyddyn ta dwi'm yn gwbod be' o'dd o ond ie o'dd hwnna efo yym Hellraiser yym Jason Michael Myers yym ia yr yr yr movie fatha",
	},
	{
		ID:    17,
		Start: 187.452,
		End:   188.813,
		Text:  "ghosts and goblins i gyd ia?",
	},
	{
		ID:    18,
		Start: 191.514,
		End:   191.574,
		Text:  "mhm.",
	},
	{
		ID:    19,
		Start: 191.594,
		End:   192.734,
		Text:  "Blen i jyst jyst it's the cast.",
	},
	{
		ID:    20,
		Start: 192.754,
		End:   194.435,
		Text:  "Dio bo' chi'n clywad hwnna yn y cast ia?",
	},
	{
		ID:    21,
		Start: 194.515,
		End:   195.575,
		Text:  "Dim ghosts ia?",
	},
	{
		ID:    22,
		Start: 196.136,
		End:   196.276,
		Text:  "ia.",
	},
	{
		ID:    23,
		Start: 196.476,
		End:   201.038,
		Text:  "Wel yy ma' hwn yn Odpeth so yy os dach chi isio meddwl ma' ghost ia?",
	},
	{
		ID:    24,
		Start: 201.058,
		End:   202.698,
		Text:  "meddwl ma' ghost ia ma' hwnna'n fine.",
	},
	{
		ID:    25,
		Start: 202.758,
		End:   203.559,
		Text:  "Yndi ella bod o'n adioed.",
	},
	{
		ID:    26,
		Start: 204.155,
		End:   232.505,
		Text:  "Ia yy so jyst jyst i yy jyst i ystablisio ychydig o ffeithia yy i wan ti yn supernatural enthusiast yndw dwi ddim gai jyst deud dwi ddim yn credu mewn ghost ocê dwi yy ddim yn rili supernatural enthusiast ia yym ag yy dwi yn outright sceptic ar ghost a stwff fine ag Elin dwi ddim yn supernatural enthusiast o gwbl a ddim yn credu mewn ghost a yn very sceptical o bob dim",
	},
	{
		ID:    27,
		Start: 232.619,
		End:   235.521,
		Text:  "actually ti'n ti'n heitio ghost stories wyt?",
	},
	{
		ID:    28,
		Start: 261.596,
		End:   265.878,
		Text:  "Dwi'm yn cofio be' odd o'n osdi ond ie dwi- o'n i'n gwatsiad chydig o betha fel'a ers talwm",
	},
	{
		ID:    29,
		Start: 291.817,
		End:   292.777,
		Text:  "Ie oedd hwnna'n dda.",
	},
	{
		ID:    30,
		Start: 292.918,
		End:   301.822,
		Text:  "Oedd hwnna'n straeon ysbryd ar ysbryd y rack hefyd dwi'n cofio achos ma' na ma' na un olygfa sydd di aros efo fi trwy'r bywyd fi gyd iawn o'n i'n t- hen nain oeddech chdi?",
	},
	{
		ID:    31,
		Start: 301.842,
		End:   317.61,
		Text:  "O'n i yna ag o'n i o- yy dwi tair mlynedd yn fengach oddech chdi o'dd hwnna'n disgard i fi fatha wnes i golli gymaint o gwisg achos o'n i'n rili ifanc so ma' raid ma' hwnna'n first memory ia o'n i o'n i'n fatha chwech dwi'n meddwl o'n i'n fatha chwech dwi'n meddwl o'n i'",
	},
	{
		ID:    32,
		Start: 320.828,
		End:   325.192,
		Text:  "dwi'm yn gwbod pam ond fatha ryw sŵn sgratsio ia?",
	},
	{
		ID:    33,
		Start: 325.612,
		End:   343.248,
		Text:  "ia ryw ryw yy berson yn stafell welo i nhw a wedyn oedd yna ryw sgw- sŵn sgratsio yym a wedyn nath y person yma agor curtains ia a beodd tu ôl i'r curtains a oedd yna hen ddynas yn sgratsio ffenast yy oedd o'n disgusting oedd o'n horrible ia a oedd o'n disgusting oedd o'n horrible ia a oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd oedd o",
	},
	{
		ID:    34,
		Start: 343.507,
		End:   372.209,
		Text:  "so ma' raid bo' ti'n floatio neu wbath fatha Ne ma' raid achos o'dd o fatha tibod first first story Wel ne o'dd o acos Bedrwm o'dd o ne bungalow o'dd o Ne bungalow ne first story yym so ia o'dd o so ti'n gwybod d- dwi dwi licio ghost dwi licio ghost stories dydi hwn ddim yn cyfres o jyst ghost stories yym so o'n i'n mynd i neud yr un gynta amdan Covid oh god ok iawn a pam bo' Covid yn supernatural dach chi'n gofyn?",
	},
	{
		ID:    35,
		Start: 373.012,
		End:   383.22,
		Text:  "ia dydi o ddim yna ia dydi o ddim yna so cause hen d- he- oce hen di notes fi iawn fatha dach chi di cl- dach chi dach chi nabod anti-maskers?",
	},
	{
		ID:    36,
		Start: 384.521,
		End:   401.175,
		Text:  "yy dim outright dim nabod dwi'm yn meddwl dwi'm yn meddwl na na yym ma' Mew yn absolute chaos fatha agent of chaos yn fama de ma' hi'n ma' hi'n atacio fo fatha yy",
	},
	{
		ID:    37,
		Start: 402.449,
		End:   404.811,
		Text:  "dwi'm yn me'wl sa- dwi'm yn me'wl sa' hi'n yy anti-masker wall.",
	},
	{
		ID:    38,
		Start: 405.472,
		End:   406.233,
		Text:  "Ie sai'n me'wl.",
	},
	{
		ID:    39,
		Start: 406.253,
		End:   407.794,
		Text:  "Definate anti-masker though.",
	},
	{
		ID:    40,
		Start: 411.298,
		End:   412.359,
		Text:  "Na, dim isie hynna.",
	},
	{
		ID:    41,
		Start: 413.9,
		End:   414.881,
		Text:  "Wel, na fo.",
	},
	{
		ID:    42,
		Start: 415.462,
		End:   415.802,
		Text:  "Yym.",
	},
	{
		ID:    43,
		Start: 415.922,
		End:   417.764,
		Text:  "O'n i'n cutio hyn.",
	},
	{
		ID:    44,
		Start: 417.784,
		End:   418.565,
		Text:  "Wna i anghofio.",
	},
	{
		ID:    45,
		Start: 418.965,
		End:   422.749,
		Text:  "So yym.",
	},
	{
		ID:    46,
		Start: 422.829,
		End:   423.87,
		Text:  "Na, o'n i jyst angen byddu i hyn le.",
	},
	{
		ID:    47,
		Start: 423.95,
		End:   424.751,
		Text:  "Ie.",
	},
	{
		ID:    48,
		Start: 424.771,
		End:   425.071,
		Text:  "Just that.",
	},
	{
		ID:    49,
		Start: 425.333,
		End:   439.222,
		Text:  "so yym ia fatha tibod dwi- dwi'n nabod dipyn o bobl sydd yn anti-covid tibod yym yn enwedig ar Facebook o ballu maen nhw'n s- maen nhw'n peddlo conspiracies pobol sydd yn cymryd yy be di enw o?",
	},
	{
		ID:    50,
		Start: 439.342,
		End:   453.512,
		Text:  "Invermectin o ia ivermectin ivermectin yym maen nhw'n cymryd hwnna pobol sy'n gwrando ar Joe Rogan a cymyn fel o ia dyna yndi that's my life philosophy ia ia!",
	},
	{
		ID:    51,
		Start: 454.07,
		End:   478.028,
		Text:  "dwi'n meddwl bod dipyn o bobl felna de, pobol sydd yn ddim di cymryd y vaccine mm so pro- fatha d- dwi'n meddwl yy ia ia pob- pobol sydd jyst tibod fatha yym ia ma'n weird be di fatha criteria bobol am fatha medical legitimacy wel ma' lot ma' lot ohno fo hefyd yn hiliol dwi'n meddwl ocê iawn?",
	},
	{
		ID:    52,
		Start: 478.541,
		End:   501.916,
		Text:  "dwi'n meddwl bod gynnoch chdi cross-section fatha fatha Venn diagram gynnoch chdi'r anti-science lot iawn a dwi'n meddwl bod gynnoch chdi rei- fatha right-wingers fatha hefyd sy jyst fatha tibod yr un pobol sy'n vote i Brexit yr un pobol dwi isie dwi isie beud ma' fel fel o'dd yn y seventies a dwi'n meddwl lack of empathy ydi lot ohno fo ia.",
	},
	{
		ID:    53,
		Start: 502.568,
		End:   528.637,
		Text:  "Ie dwi'n meddwl bo' chdi'n neud a dwi'n meddwl bo' na ben diagram gynna chdi'r dau bubble yna reit yn y canol fatha a gynnoch chdi ia y conspiracy theories ma'n dod allan ella a yym ho ti'n drapio dy hun i fyny mewn blancad fel yna wel d- gyn- dwi'n gwisgo short sleeves a ma' Mew yn yy scratchio ar hyn o bryd dan ni'n trio dysgu beidio gynnoch chdi yym gynnoch chdi rip yn dy jeans hefyd Mew nath hwnna ia.",
	},
	{
		ID:    54,
		Start: 529.855,
		End:   556.84,
		Text:  "'di o ddim yn yy ffasiynol yy yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi yndi y",
	},
	{
		ID:    55,
		Start: 560.265,
		End:   562.146,
		Text:  "so ia ma'n tibod pan bo'n hiliol?",
	},
	{
		ID:    56,
		Start: 589.309,
		End:   602.751,
		Text:  "Ia ia ma' hynna ma' hynna mor hiliol na Un Nos Ola Ddaead oh ok that's that's an interesting take on nathon ni establisio bo' Un Nos Ola Ddaead yn hiliol yn y podcast?",
	},
	{
		ID:    57,
		Start: 604.012,
		End:   616.494,
		Text:  "dwi'n meddwl t'mod fatha probably de dwi'm yn meddwl dwi'n meddwl nathon ni ddeud bod o'n hiliol mae o'n hiliol tibod fatha mae o'n ma' na bit yno fo lle mae o'n referio i fatha",
	},
	{
		ID:    58,
		Start: 621.118,
		End:   650.019,
		Text:  "pob- pobol yym d- dach chi'm yn chwerthin achos bo' fi'n barned i ddweud bo' wbath yn hiliol yna na na da ni'n chwerthin ar y gath dwi'm yn gwybod wneud hynna gegin o paid a roi hynna gegin na dwi'm yn gwybod yn gegin I'm fine o bechod o mae'n iawn mae'r gegin llawn stwff iddi ond ma' na ma' na drws gwaedur rhwng ni a'r gegin dwi'n gallu gweld hyn ia ok mae hyn yn pach yn tight mae'n upset ma'n wrtho fynd i zoo yym",
	},
	{
		ID:    59,
		Start: 650.606,
		End:   661.633,
		Text:  "Iawn so eniwe ia gynna chdi'r enginydd yn y lab iawn yy bewn i'n siarad am un o saliliad yn hiliol fatha ma' yna ma' yna Dwi'n meddwl bo' hwnna bo' ni'n wneud podcast wrong yn fama ynde?",
	},
	{
		ID:    60,
		Start: 661.673,
		End:   668.958,
		Text:  "ma' yna references i yn un o saliliad i fatha yym y pobol pobol Chinese oes?",
	},
	{
		ID:    61,
		Start: 669.098,
		End:   677.323,
		Text:  "oes ma' yna ma' yna mwy na un lle ma' fatha po- tibod pob- fel yym ma'n siarad am melyn fel pers- fatha Chinaman type of thing.",
	},
	{
		ID:    62,
		Start: 678.217,
		End:   700.736,
		Text:  "o ok nes i'm rili glocio na ond fedrai ddychmygu bod hynna'n wir dwi'm yn cofio hynna ond cwl t'mod back in the day o'dd bob dim yn hiliol rŵan dwi siŵr nath yym d- dwi siŵr nathon ni drafod e efo rywun ella ryw emyn yy ond ma' yna emyna rili hiliol a petha ella jyst canu emyn iddo fo o iawn ok ie ella ie.",
	},
	{
		ID:    63,
		Start: 702.159,
		End:   704.28,
		Text:  "anyway so yym Odpeth!",
	},
	{
		ID:    64,
		Start: 704.48,
		End:   725.267,
		Text:  "ond hefyd gynnoch chdi y five gee conspiracies ie ie ie bo' five gee di achosi covid nes i weld poster am hwnna yndyre fatha yn warnio ni o bo' five gee yn dwi di gweld dwi di gweld h- ie ma' pobl di printio stickers a di roi nw'n bobman do fatha yn deud tibod m-hm for controlling your blood with five gee a petha",
	},
	{
		ID:    65,
		Start: 728.899,
		End:   753.748,
		Text:  "syr yn controlling your blood ydy'r peth fatha ie that's hmm ond yd- ydyn tibod cweit j- dwi'n gor'o' chwarae devil's advocate efo fo ydi o'n od yndi tibod ydi o'n wir na ydi obviously fatha sy'n asti- fatha myn- na no way dwi ddim pobol jyst ofyn newid ydi lot ohno fo dwi'n meddwl ia neu sy jyst fatha fear of the unknown",
	},
	{
		ID:    66,
		Start: 754.633,
		End:   760.52,
		Text:  "fatha pan o'd mobile phones o'd allu yn y blaen a pobol fatha wow dwi'n gwybod lle yna ma' nw'n mynd i fraslo brain fi yuck.",
	},
	{
		ID:    67,
		Start: 760.54,
		End:   762.582,
		Text:  "Ie ma' nw'n microwidio testicles fi ia yn union.",
	},
	{
		ID:    68,
		Start: 762.602,
		End:   771.873,
		Text:  "dwi'n myn' rhoi hwnna efo pocket ia ia ia ma' jyst pobol yn jyst ofyn petha newydd i lot o nw dwi'n meddwl ia ella wir ond",
	},
	{
		ID:    69,
		Start: 772.261,
		End:   797.974,
		Text:  "dwi'n meddwl rhan mowran o fo hefyd mae'n siŵr ydi cause j- j- j- jyst coincidence de fatha o ma' five gee yn ga'l ei lawnsio probably nath rywun downsio arno rywun diwrnod a nath hwnna ddweud o by the way ma' covid yn big deal ladd ie yym so ie jyst yn gweud bod ie rywun pryd falla rywun yn deffro un bore a deud oh what they building that five gee tower oh that's weird a wedyn fatha hey at the end of covid fatha ti'n gwbod ie ryw fath o",
	},
	{
		ID:    70,
		Start: 798.422,
		End:   827.778,
		Text:  "Mind felt like that ia completely fe jyst yn hollol coincidence ti'n gwybod be' hwnna hath y ffostiw fel probably the ia Brexit ti'n gwybod be' ia so acos y Brexit yn kickio off tua'r un pryd a Covid ella bod Covid jyst yn big distraction dwi'n meddwl a ma' hwnna engineered gen y llawdraeth wel ma' nhw hefyd yn definite wel ma' nhw ma' nhw hefyd yn deud hynna yndi fatha bod yr o ia yndi bod o'n engineered gyda'r gyda'r government y tu fyd i gyd fel ryw fath o false flag fatha distraction ia.",
	},
	{
		ID:    71,
		Start: 827.978,
		End:   832.622,
		Text:  "sia- siarad yn Sa hynna'n horrific p- pam o't bo' bo'n coelio yna?",
	},
	{
		ID:    72,
		Start: 833.703,
		End:   855.48,
		Text:  "Ie dwi'm yn yy wel ie m- mae'n nuts yndi fatha mae'n d- diom yn weird basically fatha mae o literally yn pandemic dan ni ma' pobl di bod yn warnio ni am flus a ballu in fact Odpeth y pennod dwytha Odpeth wnaethon ni neud oedd y monkey apocalypse a wnes i siarad yn y pennod yna a deud bod y byd yn mynd i ddod i ben iawn.",
	},
	{
		ID:    73,
		Start: 855.851,
		End:   866.315,
		Text:  "achos o flus newydd fydd mwncis yn rhoid i humans a ballu fatha yn crosio o anafiliaid achos ti'n gwybod swine flu o'dd hwnna'n big deal doedd?",
	},
	{
		ID:    74,
		Start: 866.895,
		End:   874.237,
		Text:  "a yy ma' hwn ŵan fatha ma' Covid kind of fel yr un newydd fatha'r panglin flu or whatever m-hm.",
	},
	{
		ID:    75,
		Start: 874.358,
		End:   879.399,
		Text:  "di dod o'r wet markets yn yn China achos o fatha pobol yn bita ia.",
	},
	{
		ID:    76,
		Start: 879.599,
		End:   881.12,
		Text:  "bita cig dodg m-hm.",
	},
	{
		ID:    77,
		Start: 881.578,
		End:   910.924,
		Text:  "yym fel na ma' nhw'n meddwl bo' AIDS wedi cychwyn hefyd fatha bo' rywun wedi bita chimp rywle a bod nhw wedi bod bod yy nhw wedi ga'l autoimmune deficiency o'r fatha yy odd yn disease odd chimpanzees yn ga'l ia a bod o wedi symud i humans a wedi mynd loads gwaeth tibod ond ma' dyna ma' fatha ma' pobol yn yy yn wneud lot efo ma' nhw'n mynd mewn i cynefin anifeiliaid a bethau yndi ia jyst pobol efo jyst gad anifeiliaid fel yw ia jyst gad anifeiliaid fel yw ia jyst ganol yndi wel",
	},
	{
		ID:    78,
		Start: 911.391,
		End:   912.471,
		Text:  "clone yn y gegin?",
	},
	{
		ID:    79,
		Start: 914.232,
		End:   917.673,
		Text:  "jyst coin yn y gegin.",
	},
	{
		ID:    80,
		Start: 918.514,
		End:   931.538,
		Text:  "Ie ond ella trwy wneud hynna tibod fydd- fydd- anafila di'n ga'l revenge nhw ond os ydach chi isie Ie os ydach chi isie Ie mae'n shawp yn y- mae'n hogi hogi'r yy hogi'r cyllid lly a'r claws nhw.",
	},
	{
		ID:    81,
		Start: 931.998,
		End:   939.121,
		Text:  "Ie yym so engineering lab loads o bobl yn deud ydi o ddim gwaeth na'r flu dwi'm yn gwbod bod o yndi.",
	},
	{
		ID:    82,
		Start: 940.282,
		End:   968.342,
		Text:  "fine well definitely white and blue tibod ma' ma' pobol yn marw ar ffliw hefyd ond yndy yndy ond ma' ia tibod ma'r pobol hollol iach a ifanc a petha dwi'n marw ar hwn tibod ti'n me'wl dwi'm yn nabod neb ifanc dwi'm yn nabod neb sy'n marw ar ffliw rili ond na tibod dy- dy- dy- dydi o ddim mor drwg na na dwi'n nabod cwpl sy'n marw ar covid.",
	},
	{
		ID:    83,
		Start: 969.445,
		End:   974.548,
		Text:  "sy- yn ifanc hefyd tibod fatha Ie ie ie pobol oedd yn coleg efo chdi felly ia?",
	},
	{
		ID:    84,
		Start: 974.568,
		End:   990.139,
		Text:  "ond ma- ia o'na o'na person yn coleg efo fi o'na o'na person arall yn fatha oedd yn gweithio yn Caernarfon o'n i'n nabod ond ma' jyst yn tibod ma' ma' dio dio'm di mynd i ffwrdd cweit eto ma' vaccines dwi'n meddwl yn helpu ma' Kai efo Covid ar hyn o bryd yndi dy frawd?",
	},
	{
		ID:    85,
		Start: 990.538,
		End:   990.838,
		Text:  "yndy?",
	},
	{
		ID:    86,
		Start: 990.898,
		End:   992.239,
		Text:  "wel- wel- yeah ex-Covid do?",
	},
	{
		ID:    87,
		Start: 992.299,
		End:   1019.39,
		Text:  "wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel- wel",
	},
	{
		ID:    88,
		Start: 1020.418,
		End:   1021.419,
		Text:  "ma' hynna'n bonkers?",
	},
	{
		ID:    89,
		Start: 1021.459,
		End:   1030.425,
		Text:  "fatha ma' nhw'n putting their livelihood on the line yn faned yndi os ydyn nhw'n dal covid jesus yndw colli'r teist nhw wel- bwyd nhw gyd bosti nôl rywbeth!",
	},
	{
		ID:    90,
		Start: 1030.445,
		End:   1039.811,
		Text:  "ia ella fydd o ti'm yn gwbod na yym bad times iawn yy Bill Gates ie?",
	},
	{
		ID:    91,
		Start: 1040.212,
		End:   1041.873,
		Text:  "ie bewn dan nhw?",
	},
	{
		ID:    92,
		Start: 1042.253,
		End:   1044.855,
		Text:  "wel fel os ti'n neud y job bewn dan nhw galw ti?",
	},
	{
		ID:    93,
		Start: 1045.333,
		End:   1046.254,
		Text:  "bo sy bo sy tibod?",
	},
	{
		ID:    94,
		Start: 1046.274,
		End:   1073.073,
		Text:  "O ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o ie o",
	},
	{
		ID:    95,
		Start: 1073.626,
		End:   1079.488,
		Text:  "Yy ma' philanthropy ydy pan ti'n roi pres dy hun tuag at achos fi'n dda ia?",
	},
	{
		ID:    96,
		Start: 1079.868,
		End:   1081.608,
		Text:  "Ie a ma' Bill Gates yn neud hynna yndi?",
	},
	{
		ID:    97,
		Start: 1082.209,
		End:   1082.349,
		Text:  "Yndi.",
	},
	{
		ID:    98,
		Start: 1082.369,
		End:   1092.312,
		Text:  "Dwi'n meddwl bod o wedi roid Dwi'n meddwl bod o wedi roid fatha dros hanner net worth neu wbath i ff- Do ond nw probably wedi roid y thirty billion neu wbath i elusenau ond gynna fo dal thirty billion yn un bob galw na ia.",
	},
	{
		ID:    99,
		Start: 1092.332,
		End:   1094.952,
		Text:  "dydi o byth angen pre- dydi o byth na, dy boi ma' angen pres na?",
	},
	{
		ID:    100,
		Start: 1095.373,
		End:   1096.213,
		Text:  "Na dydi o ddim nadi.",
	},
	{
		ID:    101,
		Start: 1096.673,
		End:   1102.115,
		Text:  "Na ti'n gwbod os o' gynno fi billions o bunna swn i'n roid o i teg at achos Dafydd?",
	},
	{
		ID:    102,
		Start: 1102.155,
		End:   1103.375,
		Text:  "Na ia.",
	},
	{
		ID:    103,
		Start: 1103.985,
		End:   1130.067,
		Text:  "ma- ma' Mew yn absolutely miawio fatha'n rili uchel jyst jyst i un miaw bach oedd o oce nath hi neud few dwi me'wl o do oce o'dd o'n mynd mwy yy gradually fwy uchel tan o reit yym so ia Bill Gates ma' pobol yn meddwl bod o yn implantio chips yn pobol i ddechra fo sy'n kind of neud sense yndi ma' boi boi di ga- neud pres allan o Microsoft",
	},
	{
		ID:    104,
		Start: 1130.401,
		End:   1159.266,
		Text:  "so so microchips chips yeah ella bo' hynna yn the realm of fatha tibod y things fysa fo'n wneud m-hm ia s- wel na ddo nach- pam pam sa fo pam sa fo'n bod yn rhan ni'n tracio pobol peth arall dwi fydio ffyni iawn ydyw pobol yn ddeud bo' maxis yn gallu tracio pobol iawn bo' nhw'n injectio pobol ddim mwy'n tracio nhw ia fatha bo' chdi'n injectio tracking device arnoch chdi ia fatha fatha bo' nhw jyst yn popio fyny ar fatha ryw world map or whatever",
	},
	{
		ID:    105,
		Start: 1160.742,
		End:   1167.004,
		Text:  "we've got we've got Susan there she is she's going to Tesco's",
	},
	{
		ID:    106,
		Start: 1191.425,
		End:   1210.931,
		Text:  "ond yy ma' hi'n neud yy pack off ar y funud jyst bownsio'n off off bob dim it's cold yym so nawn ni canu cymryd diwedd chi yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy yndy y",
	},
	{
		ID:    107,
		Start: 1212.159,
		End:   1225.464,
		Text:  "yn tracio ni gyd efo vaccines yma ydy o di o- ydy o di orchestrated Covid er mwyn gallu gwerthu vaccines i'r llywodraeth a neud mwy o bres?",
	},
	{
		ID:    108,
		Start: 1225.484,
		End:   1229.305,
		Text:  "a sori o'n i'n meddwl bo' chdi'n mynd i gael ryw follow-up gwestiwn yy na!",
	},
	{
		ID:    109,
		Start: 1241.417,
		End:   1254.105,
		Text:  "sefydlade iechyd wedi trio gorodd arno fo dwi me'wl bod o mor syml a hynna ond ma' pobl yn licio but is the true pandemic globalism?",
	},
	{
		ID:    110,
		Start: 1254.145,
		End:   1262.21,
		Text:  "ie t'mo' m-hm ie good point I guess pan bo- ie pam bo' pobl yn hate your globalism?",
	},
	{
		ID:    111,
		Start: 1263.21,
		End:   1266.872,
		Text:  "dwi'm yn gwbod probably achos o'r system fatha t'mo' mae o'n",
	},
	{
		ID:    112,
		Start: 1269.258,
		End:   1294.866,
		Text:  "Wel ti'n meddwl fatha efo hwn fysa chdi'n meddwl back in the day tasa na rwbath wedi dod allan ym Mhrydain neu yng Nghymru neu ryw bentra yng Nghymru neu wbath oedd pobol yn mynd a dod cyn lleuad sa fo'n anhebygol iawn bod o wedi sbredio gymaint a mae wedi ŵan oedd pobol yn fflio efo man ag yn t'od fatha efo yym yy Black Death neu beth bynnag iawn oedd yym",
	},
	{
		ID:    113,
		Start: 1295.742,
		End:   1301.204,
		Text:  "Yy ma' hwnna'n wbathach ma' anti-vaxxers yn deud fatha well that went away.",
	},
	{
		ID:    114,
		Start: 1301.284,
		End:   1307.087,
		Text:  "O'dd o'n lladd traean o Ewrop fatha yeah it went away.",
	},
	{
		ID:    115,
		Start: 1307.167,
		End:   1318.131,
		Text:  "Yy o'dd o'dd yy o'dd y Black Death o'dd ma' ma' haneswyr yn gallu gweithio a- ma' nhw ma' nhw wedi gweithio allan yr union person o'dd wedi dod â'r Black Death i'r Alban.",
	},
	{
		ID:    116,
		Start: 1319.019,
		End:   1329.324,
		Text:  "achos fatha o'na cyn lleiad o fatha back and forth a traflo a ballu oedden nhw'n gwbod yn union pwy oedd wedi dod ar a sut oedd o wedi spreadio fatha yn yr cymuned yna tibod?",
	},
	{
		ID:    117,
		Start: 1329.984,
		End:   1339.129,
		Text:  "so ie ond dwi'm dwi'n meddwl bod dwi'n meddwl bod trafeilio'n peth da dwi'n meddwl bod bod powb angen fatha mynd mynd a gweld y byd tibod dwi'n meddwl bod hwnna'n bwysig.",
	},
	{
		ID:    118,
		Start: 1339.94,
		End:   1355.938,
		Text:  "Ie dwi fatha dwi'n dallt yr objections i globalism ydi bod fatha pŵar dros y byd i gyd yn mynd i ga'l ei fatha tibod neilltuo i llond llaw o bobl ond fatha jyst hynna ydi'r",
	},
	{
		ID:    119,
		Start: 1356.408,
		End:   1359.271,
		Text:  "be sy'n digwydd yn bob gwlad eniwe tibod?",
	},
	{
		ID:    120,
		Start: 1359.311,
		End:   1371.922,
		Text:  "wel be sy ie be sy'n weird ydi fatha Cymru er enghraifft iawn mm dan ni byth di bod hynna'n dda efo globalism rili dan ni'm hyd yn oed fatha fatha gwlad wedi gallu dod yn un erioed ti'n gwybod?",
	},
	{
		ID:    121,
		Start: 1372.002,
		End:   1383.532,
		Text:  "oedd gynnoch chdi fatha oedd gynnoch chdi brenhindot yn y yn y de a yn y yn Gwynedd a wedyn un arall ti'n gwybod fatha ma' na wastad tywysogion gwahanol di bod ar draws Cymru",
	},
	{
		ID:    122,
		Start: 1384.053,
		End:   1408.791,
		Text:  "efo eu kingdoms gwahanol ond dyna beth di rili uno tan i fatha Prydain ddeud Edward y cyntaf iawn ia hwn di'r lein ŵan dach chi i gyd yn Cymru ochr yr yna jyst Cymru iawn dach chi'm yn fatha Wales yeah Wales yym so ie fatha o ran globalism dwi dwi tibod fatha o'n i'n ormai yn meddwl bo' fi'n Libertarian",
	},
	{
		ID:    123,
		Start: 1409.804,
		End:   1437.734,
		Text:  "ond wedyn ma' connotations hynna ŵan yn O elli di'm bod yn ly- elli di'm bod yn Libertarian rŵan ma' wnna'n mental Libertarians ydi'r anti-maskers a a fatha yy anti- anti-maskers anti-faskers ia yym newid hinsawdd ok iawn ydi Covid di stopio newid hinsawdd neu ydi o'n ryw fath o plot i stopio newid hinsawdd yy na ond dwi'n meddwl bod o wedi helpu",
	},
	{
		ID:    124,
		Start: 1438.439,
		End:   1459.786,
		Text:  "rhywfaint a ma'r diffyg teithio di helpu o ran tibod fiwl on wedyn ma' na lot mwy o wastraff fatha plastic masks ma' pobol yn iwsio unwaith a betha ma' hynna ie ma'n balansio tibod so mae'n siŵr bod o rywsut wedi ryw balansio hyn allan ond ma' na lot llai o",
	},
	{
		ID:    125,
		Start: 1460.384,
		End:   1490.01,
		Text:  "o'dd lockdown bendant wedi helpu efo o tibod efo efo pollution yna wnawn ni deud gwybod loads rhai o geir a ballu a wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni wnawn ni w",
	},
	{
		ID:    126,
		Start: 1491.698,
		End:   1498.282,
		Text:  "fatha ydy ydy Covid wedi ga'l ei orchestrate e er mwyn creu police state?",
	},
	{
		ID:    127,
		Start: 1499.382,
		End:   1519.954,
		Text:  "yym naddo na dwi'm yn gwybod dwi dwi jyst ddim yn meddwl bod o'n orchestrated o gwbl e fatha na na ella bo' fi'n bod yn naïf de dwi'm yn gwybod ella ella bo' na evil mastermind till Bill Gates Bill Gates ia yym wel Trump fysa fo ma'n siŵr ia?",
	},
	{
		ID:    128,
		Start: 1521.203,
		End:   1536.433,
		Text:  "well yes bodd mewn pŵer ond ma' pobol yn rhoi bai ar Biden rŵan wel ie ts- ie Americans ie man yeah dumbasses ond wedyn gynna chdi gynna chdi dymases yn bofan?",
	},
	{
		ID:    129,
		Start: 1536.573,
		End:   1541.756,
		Text:  "yn bo- gynna chdi dymases yn Llanrug a bobman Cwm y Glo, Llanberis, Caernarfon ydod?",
	},
	{
		ID:    130,
		Start: 1541.776,
		End:   1549.782,
		Text:  "ia ia yym ma' masks yn stopio pobol yn adlu ma' hynna'n rwbath mewn anti-masks yndi?",
	},
	{
		ID:    131,
		Start: 1551.203,
		End:   1564.405,
		Text:  "yym o'n i ddim yn bwriadu eniwe so nes i ddweud ar y cychwyn o'n i ddim yn bwriadu siarad am Covid yn y pennod yma o ia o'n i isie siarad am pam bod y sefydliad adar i gyd yn ffêc iawn yym ocê?",
	},
	{
		ID:    132,
		Start: 1564.445,
		End:   1579.308,
		Text:  "ond dan ni di neud pennod fan'na ma' i gyd di bod am Covid a does dim byd supernatural di rili dod o arno fo so dwi'n teimlo bo' ni di wastio amser ni a pawb sy'n gwrando fo a ma'n ychydig o syna spooky yn dod yn y cefndir achos o'r cath ia do ia.",
	},
	{
		ID:    133,
		Start: 1580.026,
		End:   1586.31,
		Text:  "yym so in in summary iawn ydy Covid yn od?",
	},
	{
		ID:    134,
		Start: 1586.37,
		End:   1591.494,
		Text:  "yndi I suppose ma'n od ond ma' na lot o fod i rhagweld fo ia mynd yw ia.",
	},
	{
		ID:    135,
		Start: 1591.514,
		End:   1608.466,
		Text:  "diom- diom yn supranational ddo a diom ddim yn a- fatha mae o wedi digwydd o blaen hefyd fatha ti'n deud a ma' na betha'n tydi fatha yr fleas oedd e stalwm y pandemics a betha so od iawn i ni fatha profiad gorod byw drwyddo fo ond",
	},
	{
		ID:    136,
		Start: 1609.36,
		End:   1636.675,
		Text:  "y Spanish flu o'dd yr un arall ia a dwi'n meddwl achos adeg yna o'dd o ddim social media ella bod y theories bonkers heb di-sbredio gymaint o ond o'dd ma' na da- definitely dal yna o'ddan tibod ia bysa ma' na bunch o bobl probably dal yn meddwl o ia ond o- hefyd yn yym yn ystod yy yr Spanish flu o'dd pobol yn gwisgo masks ti'n g'bod mm fatha ma' na llunia black and white fatha ia.",
	},
	{
		ID:    137,
		Start: 1638.643,
		End:   1646.55,
		Text:  "yym o bobl mewn masks a ballu mynd a- out and about their day achos o'na pobol yn marw ma' miw yn brath i chdi fanwl.",
	},
	{
		ID:    138,
		Start: 1651.455,
		End:   1651.675,
		Text:  "yndi.",
	},
	{
		ID:    139,
		Start: 1651.695,
		End:   1651.995,
		Text:  "cute for me.",
	},
	{
		ID:    140,
		Start: 1652.015,
		End:   1652.275,
		Text:  "Ma'n uchel.",
	},
	{
		ID:    141,
		Start: 1652.375,
		End:   1656.579,
		Text:  "oes yndi yd- mae o- mae'n edrych yn cute ond mae'n actio'n vicious.",
	},
	{
		ID:    142,
		Start: 1657.881,
		End:   1660.042,
		Text:  "ia sa fatha deg waith o seis a di bita unrywun.",
	},
	{
		ID:    143,
		Start: 1661.152,
		End:   1677.48,
		Text:  "fysa fysa sa isie swatio chi o gwmpas y room cyrff chi a wedyn swatio chi o gwmpas fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa fysa",
	},
	{
		ID:    144,
		Start: 1677.978,
		End:   1679.899,
		Text:  "Wel ia o'dd o'm yn od iawn rili nagoedd?",
	},
	{
		ID:    145,
		Start: 1679.939,
		End:   1700.83,
		Text:  "Na ond welwch chi drafod dwi me'wl pennod nesa dwi me- dwi'n meddwl gawn ni j- ia just in summary iawn fatha dwi me'wl ma'na lot o pobl stupid yn y byd yma sydd yn anti ma- anti-masques yn deud peidiwch â tibod fatha dim dim dynas arnyn nhw anti-masques fatha fatha fatha yym tibod fatha dyn lady neu wbath fatha",
	},
	{
		ID:    146,
		Start: 1702.551,
		End:   1731.621,
		Text:  "ond tibod ma' na lot o bobl yn a- anti-masks a ma' ma' surgers surgeons di bod yn gwisgo masks yn neud operations am oria fatha at the time efo dim traffarth yr un masks yw fatha dan ni'n gwisgo rili de yym a mewn factories bwyd a ballu so bo- pobol ddim yn tagu drosto bwyd a tibod bobol di gwisgo masks di o ddim yn issue jyst jyst fatha hollandydd fydd o erioed ia a ella bo' fi di mynd amdan hwn a mae'n cael e'n gaeaf achos o masks ia achos",
	},
	{
		ID:    147,
		Start: 1732.671,
		End:   1733.512,
		Text:  "what?!",
	},
	{
		ID:    148,
		Start: 1733.812,
		End:   1737.356,
		Text:  "Ie pawb gwisgo masks Calan Gaea a mae'n Calan Gaea.",
	},
	{
		ID:    149,
		Start: 1737.816,
		End:   1740.84,
		Text:  "Be' na neb gwisgo masks Calan Gaea yma.",
	},
	{
		ID:    150,
		Start: 1741.06,
		End:   1741.761,
		Text:  "Ti'm yn meddwl?",
	},
	{
		ID:    151,
		Start: 1741.781,
		End:   1743.723,
		Text:  "Na ma' nhw'n sick arnyn nhw.",
	},
	{
		ID:    152,
		Start: 1743.743,
		End:   1746.265,
		Text:  "Dwi'n meddwl gwisgo masg a roid masg ar y masg hefyd.",
	},
	{
		ID:    153,
		Start: 1746.466,
		End:   1746.766,
		Text:  "Ie.",
	},
	{
		ID:    154,
		Start: 1747.226,
		End:   1747.467,
		Text:  "Ie.",
	},
	{
		ID:    155,
		Start: 1747.687,
		End:   1750.71,
		Text:  "So fatha ma' Scream yn mynd rownd ond fatha efo masg.",
	},
	{
		ID:    156,
		Start: 1750.73,
		End:   1750.99,
		Text:  "Ie.",
	},
	{
		ID:    157,
		Start: 1751.731,
		End:   1752.772,
		Text:  "Ie hynna hynna fydd yn iawn.",
	},
	{
		ID:    158,
		Start: 1752.792,
		End:   1753.273,
		Text:  "Sut pob masg?",
	},
	{
		ID:    159,
		Start: 1753.333,
		End:   1753.373,
		Text:  "Ie.",
	},
	{
		ID:    160,
		Start: 1753.985,
		End:   1770.347,
		Text:  "double masks double masks on ma' ma' na'n pobol di neud yy ar brofion lle ma' nw'n gwisgo double masks ond eniwe ia fatha jyst jyst i swymio fyny iawn ma' Covid yn beryg ia a fatha dwi'n gwbod bo' Boris Johnson yn absolute idiot iawn a dan ni'm yn twistio fo na o absolutely ddim pwys- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w- w",
	},
	{
		ID:    161,
		Start: 1770.367,
		End:   1783.79,
		Text:  "mae o di deud hefyd diom misio lockdown arall let the bodies pile high ond y ffaith ydi ond os di'r experts yn deud gwisgwch masg os di'r experts yn deud carwch ymlaen i socially distancio os di'r experts yn deud",
	},
	{
		ID:    162,
		Start: 1784.991,
		End:   1805.498,
		Text:  "vaccinati- fiwch a ga'l yy booster shots a bob dim wel rhaid i ni wrando ar yr experts ma' nw di ma' n- ma' nw'n nw sy'n gwbod a sy- a ma' nw'n gwbod o well na ni ma' nw'n gwbod o well iawn na fatha Ryan lawr y pub sydd yn mynd i ddeud fatha o ia na ma' ma' 5G yn rheoli gwaed dwi a dwi- dwi'm yn tristio Bill Gates fatha",
	},
	{
		ID:    163,
		Start: 1807.056,
		End:   1815.299,
		Text:  "rha- rhaid i chdi cyrra boed lle ti'n meddwl iawn ocê ma' ma' ma' rhein yn mental ma'r pobol yma ma' na jyst ma' nhw di mynd off the edge tibod?",
	},
	{
		ID:    164,
		Start: 1815.479,
		End:   1834.947,
		Text:  "Ie ie fatha Ie mae o'n yy d- odd yr un peth efo Brexit fatha oedd tibod odd hi'n gweld ar y teli expert of economics yn neud fatha professor of economics yn Cambridge neu wbath yn deud ia ma' hyn yn rili syniad awful ia a wedyn y person oedden nhw'n galw yn erbyn hynna oedd fatha Wendy",
	},
	{
		ID:    165,
		Start: 1835.776,
		End:   1854.809,
		Text:  "o- one day from you kid yeah ne ne ne ne ma' nw'n o ie it's going to be gre- o ie ma' nw'n mynd na ma' n- ma'r news di mynd yn shit de achos cynt ne dwi'm yn gwbod so oedd o cynt ella bo' nw wastad wedi neud hyn ond fox pops!",
	},
	{
		ID:    166,
		Start: 1855.009,
		End:   1884.054,
		Text:  "ma' nhw jyst yn mynd allan ar y stryd a gofyn am barn pobol fatha jyst ar y stryd fatha so yym yy yy yy thanks thanks that was a David Solomon the the chief economic fatha yy lecturer at Cambridge University who tells us that Brexit is a bad idea but we've been on the streets of Essex and we've spoken to Tracey ti'n gwbod fatha so Tracey yeah we don't want him here or whatever ti'n gwbod fatha thank you Tracey ia dwi'n meddwl fel chdi os ti'n mynd i ga'l pobol rai' chdi ga'l",
	},
	{
		ID:    167,
		Start: 1885.162,
		End:   1888.345,
		Text:  "pobol o'r un clant ia ti'n gwbo be' dwi'n feddwl?",
	},
	{
		ID:    168,
		Start: 1888.445,
		End:   1893.631,
		Text:  "ond ond hynna ydi'r problem achos fatha hi- os ti'n sbïo ar fy hunan bellach ti'n gwbo?",
	},
	{
		ID:    169,
		Start: 1893.691,
		End:   1897.915,
		Text:  "fatha oce be' di'r criteria bo' nw efo degree iawn?",
	},
	{
		ID:    170,
		Start: 1898.496,
		End:   1898.916,
		Text:  "wel-",
	},
	{
		ID:    171,
		Start: 1899.633,
		End:   1909.518,
		Text:  "o'dd Trump university thing o'dd pobol yn gallu talu Donald Trump i ga'l degrees so elli di hynna trustio pobol efo degrees ddim fwy rili ti gwbo?",
	},
	{
		ID:    172,
		Start: 1910.038,
		End:   1923.786,
		Text:  "a hynna ydi'r problem achos os ti methu trustio pobol efo degrees neu pobol sydd wedi neud sydd efo doctorates neu wedi astudio neu beth bynnag wel pwy ti yn gallu trustio wyt ti jyst yn gorffen yn un tro at Joe Rogan dwi'n meddwl",
	},
	{
		ID:    173,
		Start: 1924.514,
		End:   1950.091,
		Text:  "dwi'n meddwl rhaid i chdi ga'l fatha s- tibod fatha critical pawb fod yn critical jyst jyst o pwy ma' nhw'n gwrando ar a fatha lle ma' nhw'n ga'l newyddion nhw a a tibod fatha fatha peidiwch gwrando arna ni oh my god na tibod dim ni ydi'r experts yn fa'fa na ewch allan ffeindiwch experts ia peidiwch yn dweud o ia dwi dwi tibod dwi dwi dwi dwi yn mynd i ga'l vaccine achos ma' you and pitch di ddeud-.",
	},
	{
		ID:    174,
		Start: 1950.503,
		End:   1971.411,
		Text:  "fatha fo- fod five gee ddim yn gwaed i fi paidwch yy paidwch yn gwrando arna fi fatha randwch ar be ma'r experts yn ddeud neu- newch be ma'r experts yn neud a wsos nesa dwi efo ghost i chi so excellent ok iawn so happy Halloween pawb a nawelwch chi wsos nesa ia oedd o'n yn benod spooky iawn oedd o nagoedd?",
	},
	{
		ID:    175,
		Start: 1971.651,
		End:   1979.334,
		Text:  "nagoedd ond dwi'n meddwl oedd o'n oedd rhaid i ni neud o yeah kind of the way kind of bwysig efyd dwi'n meddwl tibod mm ia mae o'n pwy- mae o'n pwysig",
	},
	{
		ID:    176,
		Start: 1980.35,
		End:   1981.906,
		Text:  "anyway ta-ta!",
	},
}
